// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Coupon struct {
	CouponID    uuid.UUID        `json:"coupon_id"`
	Code        pgtype.Text      `json:"code"`
	Discount    pgtype.Numeric   `json:"discount"`
	MinPurchase pgtype.Numeric   `json:"min_purchase"`
	StartAt     pgtype.Timestamp `json:"start_at"`
	ExpiresAt   pgtype.Timestamp `json:"expires_at"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Review struct {
	ReviewID  uuid.UUID        `json:"review_id"`
	UserID    uuid.UUID        `json:"user_id"`
	ProductID string           `json:"product_id"`
	Rating    pgtype.Numeric   `json:"rating"`
	Comment   string           `json:"comment"`
	Status    string           `json:"status"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Wishlist struct {
	WlID      uuid.UUID        `json:"wl_id"`
	UserID    uuid.UUID        `json:"user_id"`
	ProductID string           `json:"product_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
